name: arXiv Paper Crawler

on:
  schedule:
    - cron: '0 22 * * *'  # UTC 22:00
  workflow_dispatch:

jobs:
  crawl-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv
        pip install python-dotenv
    
    - name: Run crawler and send email
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        TOPICS: ${{ vars.TOPICS }}
      run: |
        python -c "
        from src.crawler import fetch_arxiv_papers, format_email_content
        from src.mailer import send_email
        import os
        
        # 获取配置
        topics = os.environ.get('TOPICS', '')
        
        # 获取论文
        papers_by_topic = fetch_arxiv_papers(topics)
        
        # 格式化并发送邮件
        content = format_email_content(papers_by_topic)
        send_email(content, os.environ.get('RECIPIENT_EMAIL'))
        "
