name: DBLP Paper Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  crawl-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run crawler and send email
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        KEYWORD: "multimodal learning"  # 可以根据需要修改关键词
      run: |
        python -c "
        from src.crawler import fetch_dblp_papers, format_email_content
        from src.mailer import send_email
        import os
        
        papers = fetch_dblp_papers(os.environ.get('KEYWORD'))
        content = format_email_content(papers)
        send_email(content, os.environ.get('RECIPIENT_EMAIL'))
        "